### ISSUE TITLE
new long image view

### ISSUE THREAD

**Issue by SammyVimes** [futurobot/Long-Images-with-Glide#1]
Hi! Just wanted to ask why are you writing new 'ImageView', I thought you got one in your pikabu client.  Is it because of glide?

**Comment by kalyaganov** [comment]
@SammyVimes в клиенте было отображение длинных изображений с помощью модифицированной библиотеки picasso. Мне не нравилось как это сделать, потому что приходилось таскать всю модифицированную библиотеку с собой и трудно было ее обновлять до последней версии picasso. Поэтому я решил использовать glide, так как он позволяет почти "из коробки" декодировать часть изображений. То решение, что в клиенте пикабу - почти тоже самое, только изображение декодируется при помощи picasso. Но в целом я думаю что эти библиотеки все-равно тяжелые чтобы декодировать изображения на лету в ленте. По хорошему нужно на одно изображение создавать один RegionDecoder и использовать его, это позволит увеличить производительность и ускорить процесс. Сделаю в будущем отображение основанное на этой библиотеке https://github.com/diegocarloslima/ByakuGallery

**Comment by SammyVimes** [comment]
Хм, я в последнее время склоняюсь к мысли, что без плюсов не получится сделать, потому что джава тупо не даёт выделить достаточно памяти.
Btw, вы видели библиотеку https://github.com/davemorrissey/subsampling-scale-image-view ?

**Comment by kalyaganov** [comment]
@SammyVimes Видел когда-то. С плюсами сложно будет контролировать память и появятся потенциальные проблемы на устройствах с малым объемом оперативной памяти. Джава может достаточно быстро декодировать изображения. Чтобы смягчить эффект подгрузки тайлов можно сначала рисовать полное изображение в низком разрешении на фоне, а поверх нужный тайл, когда он будет готов. В приложении 9gag они разрезают изображения на готовые тайлы и сохраняют каждый в отдельный файл. Наверное этим они избавляются от RegionDecoder и каким-то образом оптимизируют использование памяти.

Вообще, наверное, имеет смысл вынести все декодирование в плюсы - тогда можно будет добиться прироста производительности.

**Comment by SammyVimes** [comment]
@futurobot как раз в третьей версии SubsamplingScaleImageView добавили нативные декодеры (https://github.com/suckgamony/RapidDecoder). Ну и с отрисовкой там так и сделано (рисуем всё, потом тайлы поверх). Но всё равно может упасть, если показывать список изображений:/

**Comment by kalyaganov** [comment]
@SammyVimes если кэш использовать и правильно сэмплинг применять то не будет падать,там фиксированный размер памяти выделяться будет под все битмапы. Еще в последних версиях android появилась возможность переиспользовать битмапы(bitmap pool).
